apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: airflow.intuitive.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: airflow-service
          servicePort: 8080
